[msg Choose]
[f 0 8 -258][f 1 31]> Where would you like to go?[e]

[sel School]
[f 0 8 -258][f 1 31]School Entranceway[e]
[f 0 8 -258][f 1 31]1st Floor, Main Lobby[e]
[f 0 8 -258][f 1 31]1st Floor, Faculty Hall[e]
[f 0 8 -258][f 1 31]1st Floor, Laboratory Hall[e]

[sel School2]
[f 0 8 -258][f 1 31]1st Floor, Corridor[e]
[f 0 8 -258][f 1 31]Sports Clubs[e]
[f 0 8 -258][f 1 31]2nd Floor, Hallway[e]
[f 0 8 -258][f 1 31]Classroom 2-F[e]

[sel School3]
[f 0 8 -258][f 1 31]Rooftop[e]
[f 0 5 -258][f 1 31]Facilities[e]
[f 0 8 -258][f 1 31]Town Map[e]

[sel Mall]
[f 0 8 -258][f 1 31]Paulownia Mall[e]
[f 0 8 -258][f 1 31]Back Alley[e]
[f 0 8 -258][f 1 31]Facilities[e]
[f 0 8 -258][f 1 31]Town Map[e]

[sel MallFacilities]
[f 0 8 -258][f 1 31]Velvet Room[e]
[f 0 8 -258][f 1 31]Club Escapade[e]
[f 0 8 -258][f 1 31]Chagall Cafe[e]
[f 0 8 -258][f 1 31]Be blue V[e]

[sel MallFacilities2]
[f 0 8 -258][f 1 31]Police Station[e]
[f 0 8 -258][f 1 31]Mandragora[e]
[f 0 8 -258][f 1 31]Shinshoudo Antiques[e]
[f 0 8 -258][f 1 31]Aohige Pharmacy[e]

[sel MallFacilities3]
[f 0 8 -258][f 1 31]Crane Game[e]
[f 0 8 -258][f 1 31]Game Panic[e]

[sel Iwatodai]
[f 0 8 -258][f 1 31]Iwatodai Station[e]
[f 0 8 -258][f 1 31]Iwatodai Strip Mall, Ground Floor[e]
[f 0 8 -258][f 1 31]Iwatodai Strip Mall, Upper Floors[e]

[sel Iwatodai2]
[f 0 8 -258][f 1 31]Shops[e]
[f 0 8 -258][f 1 31]Town Map[e]

[sel IwatodaiFacilities]
[f 0 8 -258][f 1 31]Wild-Duck Burger[e]
[f 0 8 -258][f 1 31]Wakatsu Restaurant[e]
[f 0 8 -258][f 1 31]Hagakure[e]
[f 0 8 -258][f 1 31]Octopia[e]

[sel PortIsland]
[f 0 8 -258][f 1 31]Port Island Station[e]
[f 0 8 -258][f 1 31]Station Outskirts[e]
[f 0 8 -258][f 1 31]Shops[e]
[f 0 8 -258][f 1 31]Town Map[e]

[sel PortFacilities]
[f 0 8 -258][f 1 31]Rafflesia[e]
[f 0 8 -258][f 1 31]Screen Shot[e]

[msg No_QT]
[f 0 8 -258][f 1 31]You can't Quick Travel here.[n][f 0 4][e]

[msg No_Facilities]
[f 0 8 -258][f 1 31]There are no facilities in this locaiton.[n][f 0 4][e]

[msg Same]
[f 0 8 -258][f 1 31]You are already there.[n][f 0 4][e]

[msg Page1of1]
[f 0 8 -258][f 1 31]  Page 1 of 1.[n][f 0 4][e]

[msg Page1of2]
[f 0 8 -258][f 1 31]  Page 1 of 2.[n][f 0 4][e]

[msg Page2of2]
[f 0 8 -258][f 1 31]  Page 2 of 2.[n][f 0 4][e]

[msg Page1of3]
[f 0 8 -258][f 1 31]  Page 1 of 3.[n][f 0 4][e]

[msg Page2of3]
[f 0 8 -258][f 1 31]  Page 2 of 3.[n][f 0 4][e]

[msg Page3of3]
[f 0 8 -258][f 1 31]  Page 3 of 3.[n][f 0 4][e]