[msg Choose]
[f 0 8 -258][f 1 31]> Where would you like to go?[e]

[sel School]
[f 0 8 -258][f 1 31]School Entranceway[e]
[f 0 8 -258][f 1 31]1st Floor, Main Lobby[e]
[f 0 8 -258][f 1 31]1st Floor, Faculty Hall[e]
[f 0 8 -258][f 1 31]1st Floor, Laboratory Hall[e]

[sel School2]
[f 0 8 -258][f 1 31]1st Floor, Corridor[e]
[f 0 8 -258][f 1 31]Sports Clubs[e]
[f 0 8 -258][f 1 31]2nd Floor, Hallway[e]
[f 0 8 -258][f 1 31]Classroom 2-F[e]

[sel School3]
[f 0 8 -258][f 1 31]Rooftop[e]

[sel Mall]
[f 0 8 -258][f 1 31]Paulownia Mall[e]
[f 0 8 -258][f 1 31]Back Alley[e]
[f 0 8 -258][f 1 31]Club Escapade[e]

[sel PortIsland]
[f 0 8 -258][f 1 31]Port Island Station[e]
[f 0 8 -258][f 1 31]Station Outskirts[e]

[sel Iwatodai]
[f 0 8 -258][f 1 31]Iwatodai Station[e]
[f 0 8 -258][f 1 31]Iwatodai Strip Mall, Ground Floor[e]
[f 0 8 -258][f 1 31]Iwatodai Strip Mall, Upper Floors[e]

[sel Dorm]
[f 0 5 -258][f 1 31]Dorm Entrance[e]
[f 0 5 -258][f 1 31]Your Room[e]
[f 0 5 -258][f 1 31]1st Floor, Lounge[e]
[f 0 5 -258][f 1 31]2nd Floor, Hallway[e]

[sel Dorm2]
[f 0 5 -258][f 1 31]3rd Floor, Hallway[e]
[f 0 5 -258][f 1 31]4th Floor, Hallway[e]
[f 0 5 -258][f 1 31]Meeting Room[e]

[msg Page1of1]
[f 0 8 65278][f 1 31]  Page 1 of 1.[n][f 0 21 9999][e]

[msg Page1of2]
[f 0 8 65278][f 1 31]  Page 1 of 2.[n][f 0 21 9999][e]

[msg Page2of2]
[f 0 8 65278][f 1 31]  Page 2 of 2.[n][f 0 21 9999][e]

[msg Page1of3]
[f 0 8 65278][f 1 31]  Page 1 of 3.[n][f 0 21 9999][e]

[msg Page2of3]
[f 0 8 65278][f 1 31]  Page 2 of 3.[n][f 0 21 9999][e]

[msg Page3of3]
[f 0 8 65278][f 1 31]  Page 3 of 3.[n][f 0 21 9999][e]