[sel TALK_SEL top]
[f 0 8 65278][f 1 31]Add to party[e]
[f 0 8 65278][f 1 31]Check status[e]
[f 0 8 65278][f 1 31]Remove from party[e]
[f 0 8 65278][f 1 31]Done[e]

[sel BACK_UP_SEL top]
[f 0 8 65278][f 1 31]Check everyone's status[e]
[f 0 8 65278][f 1 31]Head to Club Escapade[e]
[f 0 8 65278][f 1 31]Wait for a second[e]

[sel PARTY_SEL top]
[f 0 8 65278][f 1 31]Yukari[e]
[f 0 8 65278][f 1 31]Aigis[e]
[f 0 8 65278][f 1 31]Mitsuru[e]
[f 0 8 65278][f 1 31]Junpei[e]
[f 0 8 65278][f 1 31]Akihiko[e]
[f 0 8 65278][f 1 31]Ken[e]
[f 0 8 65278][f 1 31]Shinjiro[e]
[f 0 8 65278][f 1 31]Koromaru[e]
[f 0 8 65278][f 1 31]Done[e]

[msg YUKARI_PARTY_IN [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]We'll have to deal with the wiring...[n]I have a bad feeling about this.[n][f 0 4][e]

[msg YUKARI_PARTY_IN_AFTER [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]Sure.[n][f 0 4][e]

[msg YUKARI_PARTY_OUT [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]Let's hurry![n][f 0 4][e]

[msg YUKARI_PARTY_OUT_AFTER [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]Okay. Be careful...[n][f 0 4][e]

[msg YUKARI_PARTY_OVER [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]You've already got too many[n]people with you...[n][f 0 4][e]

[msg YUKARI_PARTY_CHANGE [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]Who should I switch with?[n][f 0 4][e]

[msg AEGIS_PARTY_IN [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]Ready to go.[n][f 0 4][e]

[msg AEGIS_PARTY_IN_AFTER [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]Roger that.[n][f 0 4][e]

[msg AEGIS_PARTY_OUT [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]Let us go.[n][f 0 4][e]

[msg AEGIS_PARTY_OUT_AFTER [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]...Understood.[n][f 0 4][e]

[msg AEGIS_PARTY_OVER [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]There is no available space in[n]your party for me.[n][f 0 4][e]

[msg AEGIS_PARTY_CHANGE [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]Who shall I switch places with?[n][f 0 4][e]

[msg MITSURU_PARTY_IN [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]I'm surprised that Shadow took over[n]the underground cables...[n][f 0 4][e]

[msg MITSURU_PARTY_IN_AFTER [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]All right, let's go.[n][f 0 4][e]

[msg MITSURU_PARTY_OUT [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]We're short on time. Hurry.[n][f 0 4][e]

[msg MITSURU_PARTY_OUT_AFTER [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]Okay... Be careful.[n][f 0 4][e]

[msg MITSURU_PARTY_OVER [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]You've got a full party already.[n][f 0 4][e]

[msg MITSURU_PARTY_CHANGE [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]Who should I replace?[n][f 0 4][e]

[msg HUKA_BACK_UP [Fuuka]]
[f 0 8 65278][f 1 31][f 0 31 6 12 1 1]Are you ready?[n][f 0 4][e]

[msg HUKA_MEMBER_INSUFFICIENC [Fuuka]]
[f 0 8 65278][f 1 31][f 0 31 6 12 1 1]It's dangerous to go to Club[n]Escapade without enough people.[n]You should reform your party...[n][f 0 4][e]

[msg HUKA_LETS_GO [Fuuka]]
[f 0 8 65278][f 1 31][f 0 31 6 12 1 1]I'm counting on you all.[n][f 0 4][e]

[msg SANADA_PARTY_IN [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]It doesn't matter what the enemy[n]takes over. I'll take it down.[n][f 0 4][e]

[msg SANADA_PARTY_IN_AFTER [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]Count on me.[n][f 0 4][e]

[msg SANADA_PARTY_OUT [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]What are you waiting for? Let's go.[n][f 0 4][e]

[msg SANADA_PARTY_OUT_AFTER [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]Tch... All right.[n][f 0 4][e]

[msg SANADA_PARTY_OVER [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]Your party's full.[n][f 0 4][e]

[msg SANADA_PARTY_CHANGE [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]Who should I switch out with?[n][f 0 4][e]

[msg AMADA_PARTY_IN [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]I wonder what happened to Junpei-san...[n][f 0 4][e]

[msg AMADA_PARTY_IN_AFTER [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]Sure, I'll do my best.[n][f 0 4][e]

[msg AMADA_PARTY_OUT [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]Let's go at once.[n][f 0 4][e]

[msg AMADA_PARTY_OUT_AFTER [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]Okay... I'll be waiting here.[n][f 0 4][e]

[msg AMADA_PARTY_OVER [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]Your party is full...[n][f 0 4][e]

[msg AMADA_PARTY_CHANGE [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]Who should I replace?[n][f 0 4][e]

[msg ARAGAKI_PARTY_IN [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]Let's go.[n][f 0 4][e]

[msg ARAGAKI_PARTY_IN_AFTER [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]...You can count on me.[n][f 0 4][e]

[msg ARAGAKI_PARTY_OUT [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]What's the matter?[n][f 0 4][e]

[msg ARAGAKI_PARTY_OUT_AFTER [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]What's wrong? Not satisfied with[n]my performance?[n][f 0 4][e]

[msg ARAGAKI_PARTY_OVER [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]Hey! You don't have an opening[n]for me.[n][f 0 4][e]

[msg ARAGAKI_PARTY_CHANGE [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]So... Who am I replacing?[n][f 0 4][e]

[msg KOROMARU_PARTY_IN [Koromaru]]
[f 0 8 65278][f 1 31][f 0 31 10 12 1 1]Arf![n][f 0 4][e]

[msg KOROMARU_PARTY_IN_AFTER [Koromaru]]
[f 0 8 65278][f 1 31][f 0 31 10 12 1 1]Arf, arf![n][f 0 4][e]

[msg KOROMARU_PARTY_OUT [Koromaru]]
[f 0 8 65278][f 1 31][f 0 31 10 12 1 1]Arf, arf![n][f 0 4][e]

[msg KOROMARU_PARTY_OUT_AFTER [Koromaru]]
[f 0 8 65278][f 1 31][f 0 31 10 12 1 1]Whine...[n][f 0 4][e]

[msg KOROMARU_PARTY_OVER [Koromaru]]
[f 0 8 65278][f 1 31][f 0 31 10 12 1 1]Woof![n][f 0 4][e]

[msg KOROMARU_PARTY_CHANGE [Koromaru]]
[f 0 8 65278][f 1 31][f 0 31 10 12 1 1]Woof! Woof![n][f 0 4][e]

[msg YUKARI_EQUIP_TRANSFER [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]For me? Thanks![n][f 0 4][e]

[msg AEGIS_EQUIP_TRANSFER [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]Is this for me?[n]I apppreciate your support.[n][f 0 4][e]

[msg MITSURU_EQUIP_TRANSFER [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]For me? Thanks a lot.[n][f 0 4][e]

[msg SANADA_EQUIP_TRANSFER [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]Huh, is this for me?[n]Thanks.[n][f 0 4][e]

[msg AMADA_EQUIP_TRANSFER [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]Really? For me?[n]Thank you very much![n][f 0 4][e]

[msg ARAGAKI_EQUIP_TRANSFER [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]For me...? Thanks.[n][f 0 4][e]

[msg KOROMARU_EQUIP_TRANSFER [Koromaru]]
[f 0 8 65278][f 1 31][f 0 31 10 12 1 1]Woof![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 16][f 0 8 65278][f 1 31][f 1 0 10 12 1]> Koromaru seems happy.[n][f 0 4][e]

[msg YUKARI_EQUIP_REACTION [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 5 1]Wh-What is this!? Are you asking[n]me to wear this...!?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 2 12 8 1]Th-This is an abuse of power...![n]*sigh* Fine...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 2 12 4 1]I just hope my friends never[n]find out...[n][f 0 4][e]

[msg YUKARI_EQUIP_SP_REACTION [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 8 1]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]I can't believe you're ordering me[n]to wear this...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 2 12 3 1]You've really let this whole "leader"[n]thing go to your head, you know that?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 2 12 8 1]......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 2 12 7 1]Fine... I'll wear it. Hope you're[n]happy...[n][f 0 4][e]

[msg AEGIS_EQUIP_REACTION [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]These must be...[n][f 0 4][e]
[f 0 8 65278][f 1 31]The clothes I wore before...[n][f 0 4][e]
[f 0 8 65278][f 1 31]They're very comfortable, and[n]easy to wear![n][f 0 4][e]

[msg AEGIS_EQUIP_SP_REACTION [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]These clothes...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 3 12 2 1]Do you prefer to see me in these[n]clothes, [f 0 11]-san...?[n][f 0 4][e]
[f 0 8 65278][f 1 31]They are not suited to battle...[n][f 0 4][e]
[f 0 8 65278][f 1 31]But I do not mind wearing them.[n]Thank you very much.[n][f 0 4][e]

[msg MITSURU_EQUIP_REACTION [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 7 1]...![n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Fine... I'll wear it for the[n]sake of the mission.[n][f 0 4][e]

[msg MITSURU_EQUIP_SP_REACTIO [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]Hm... What is this for?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 4 12 7 1]......!?[n]A-Are you seriously asking me to[n]wear this!?[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]A-Are you certain this will help in[n]battle...? I want an explanation for[n]this afterwards...![n][f 0 4][e]

[msg SANADA_EQUIP_REACTION [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 5 1]Th-This is...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 7 12 8 1]Hmph... I see.[n]It's a challenge...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]I accept! I'll wear anything[n]for victory...![n][f 0 4][e]

[msg SANADA_EQUIP_SP_REACTION [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 5 1]Hm...? Why a bathing suit?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 7 12 0 1]Well, if you want me to wear it,[n]fine with me. It's no different[n]than what I wear while I box.[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 7 12 2 1]...What? Did I say something funny?[n][f 0 4][e]

[msg AMADA_EQUIP_REACTION [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 4 1]What...? This design... It's so[n]childish...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Well, I'll do anything the leader[n]asks... But it's so childish...[n][f 0 4][e]

[msg AMADA_EQUIP_SP_REACTION [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 2 1]Oh... These are the clothes you[n]wear on...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 8 12 3 1]......!?[n][f 0 4][e]
[f 0 8 65278][f 1 31]W-Wait... you want me to wear[n]these...?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 8 12 4 1]Aaagh... Th-This is so embarassing...[n]Fine... I'll show you I'm not a kid...[n][f 0 4][e]

[msg ARAGAKI_EQUIP_REACTION [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]Hm...? Not bad.[n][f 0 4][e]
[f 0 8 65278][f 1 31]It looks good on me...[n]I'll take it![n][f 0 4][e]

[msg ARAGAKI_EQUIP_SP_REACTIO [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 3 1]......!?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]Where'd you find this...?[n][f 0 4][e]
[f 0 8 65278][f 1 31]It feels good...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Like nothin' in the world can stop[n]me now...[n][f 0 4][e]

[msg YUKARI_GRADE_UP [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]Hey, just as a heads up, I've[n]changed my equipment.[n][f 0 4][e]

[msg AEGIS_GRADE_UP [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]I have modified my equipment[n]loadout, for the record.[n][f 0 4][e]

[msg MITSURU_GRADE_UP [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]Just letting you know...[n]I've changed my equipment.[n][f 0 4][e]

[msg SANADA_GRADE_UP [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]Hey, I've changed my equipment[n]around a little.[n][f 0 4][e]

[msg AMADA_GRADE_UP [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]Before I forget, I've switched[n]my equipment.[n][f 0 4][e]

[msg ARAGAKI_GRADE_UP [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]I'm using different equipment now.[n][f 0 4][e]

[msg KOROMARU_GRADE_UP [Koromaru]]
[f 0 8 65278][f 1 31][f 0 31 10 12 1 1]Arf![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 16][f 0 8 65278][f 1 31][f 1 0 12 10 1]> Koromaru's equipment has been[n]changed.[n][f 0 4][e]

[msg YUKARI_GRADE_UP_TRANSFER [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 12 1 1]I'll return the stuff you gave[n]me before.[n][f 0 4][e]

[msg AEGIS_GRADE_UP_TRANSFER [Aigis]]
[f 0 8 65278][f 1 31][f 0 31 3 12 1 1]I will return what I had[n]borrowed.[n][f 0 4][e]

[msg MITSURU_GRADE_UP_TRANSFE [Mitsuru]]
[f 0 8 65278][f 1 31][f 0 31 4 12 1 1]I'll return the equipment you[n]gave me.[n][f 0 4][e]

[msg SANADA_GRADE_UP_TRANSFER [Akihiko]]
[f 0 8 65278][f 1 31][f 0 31 7 12 1 1]I'll return the equipment[n]you gave me.[n][f 0 4][e]

[msg AMADA_GRADE_UP_TRANSFER [Ken]]
[f 0 8 65278][f 1 31][f 0 31 8 12 1 1]I'll give back what I'd borrowed[n]from you before.[n][f 0 4][e]

[msg ARAGAKI_GRADE_UP_TRANSFE [Shinjiro]]
[f 0 8 65278][f 1 31][f 0 31 9 12 1 1]...Here's your stuff back.[n][f 0 4][e]

[msg KOROMARU_GRADE_UP_TRANSF [Koromaru]]
[f 0 8 65278][f 1 31][f 0 31 10 12 1 1]Arf![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 16][f 0 8 65278][f 1 31][f 1 0 10 12 1]> Koromaru has returned the[n]equipment that he was wearing.[n][f 0 4][e]

[msg ITEM_TRANSFER_TO_PLAYER_]
[f 0 8 65278][f 1 31][f 1 0 2 12 1][f 1 0 3 12 1][f 1 0 4 12 1][f 1 0 5 12 1][f 1 0 7 12 1][f 1 0 8 12 1][f 1 0 9 12 1]> Received [f 0 26 0 1].[n][f 0 4][e]

[msg ITEM_TRANSFER_TO_PLAYER__2]
[f 0 8 65278][f 1 31][f 1 0 2 12 1][f 1 0 3 12 1][f 1 0 4 12 1][f 1 0 5 12 1][f 1 0 7 12 1][f 1 0 8 12 1][f 1 0 9 12 1]> Received [f 0 26 0 1]. [n]  Received [f 0 26 2 3].[n][f 0 4][e]

[msg SCR_MSG_PARAM_MIRYOKU1]
[f 0 8 65278][f 1 31]> Your Charm seems to have[n]increased![n][f 0 4][e]

[msg SCR_MSG_PARAM_MIRYOKU2]
[f 0 8 65278][f 1 31]> Your Charm went from "[f 0 3 0]"[n]to "[f 0 3 1]"![n][f 0 4][e]

[msg MSG0421_09 [葛褐 轄且]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]Dude, I don't think I've ever had[n]this much money in my life.[n][f 0 4][e]
[f 0 8 65278][f 1 31]I better go deposit this in the[n]bank. Wouldn't want to lose it[n]by accident, y'know?[n][f 0 4][e]

[msg MSG0426_YUKARI_01 [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 2 1 1]What a coincidence... Did you come[n]here to shop too, [f 0 11]-kun?[n][f 0 4][e]

[sel MSG0426_YUKARI_01_SEL top]
[f 0 8 65278][f 1 31]"That's right."[e]
[f 0 8 65278][f 1 31]"I'm just wandering around."[e]

[msg MSG0426_YUKARI_02 [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 2 1 1]This mall is pretty convenient.[n]You can buy almost anything here.[n][f 0 4][e]

[msg MSG0426_YUKARI_03 [Yukari]]
[f 0 8 65278][f 1 31][f 0 31 2 2 1 1]You don't know this place? You[n]should explore the city some more.[n][f 0 4][e]

[msg MSG0619_JUNPEI_01 [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 1 1]You know I use two-handed swords,[n]right? Someday, I'm gonna find it...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 5 1 0 1]The LEGENDARY SWORD![n][f 0 4][e]

[sel MSG0619_JUNPEI_01_SEL top]
[f 0 8 65278][f 1 31]"There's no need..."[e]
[f 0 8 65278][f 1 31]"Good luck."[e]
[f 0 8 65278][f 1 31]"Find me one too."[e]

[msg MSG0619_JUNPEI_02 [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 9 1]How can you deny a man's passion[n]like that!? That's cold, bro![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 5 1 2 1]C'mon, you've gotta dream big![n][f 0 4][e]

[msg MSG0619_JUNPEI_03 [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 0 1]Thanks! I'm gonna do my best.[n][f 0 4][e]

[msg MSG0619_JUNPEI_04 [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 1 0 1]Sure thing, right? Let's hope we[n]can find it.[n][f 0 4][e]

[msg MSG0719_JUNPEI_01 [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 2 1 1]I came to pick some swimwear to[n]bring to Yakushima, but I dunno[n]which one to get.[n][f 0 4][e]
[f 0 8 65278][f 1 31]I asked Akihiko-san, but he doesn't[n]give a rip about fashion.[n][f 0 4][e]
[f 0 8 65278][f 1 31]So it's up to you, dude! Tell[n]me what I should bring![n][f 0 4][e]

[sel MSG0719_JUNPEI_01_SEL top]
[f 0 8 65278][f 1 31]"Boxers."[e]
[f 0 8 65278][f 1 31]"Speedos."[e]
[f 0 8 65278][f 1 31]"A one-piece bathing suit."[e]
[f 0 8 65278][f 1 31]"A red loincloth."[e]

[msg MSG0719_JUNPEI_02 [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 2 1 1]The basic style, huh? I dunno, is[n]that the style I should go for?[n][f 0 4][e]

[msg MSG0719_JUNPEI_03 [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 2 1 1]That's not really my thing...[n]I don't have the body for it,[n]y'know?[n][f 0 4][e]

[msg MSG0719_JUNPEI_04 [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 2 1 1]I thought of that once. It'll get[n]a laugh, at least![n][f 0 4][e]

[msg MSG0719_JUNPEI_05 [Junpei]]
[f 0 8 65278][f 1 31][f 0 31 5 2 2 1]Hell yeah! This is a REAL[n]Japanese man's swimwear![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 0 31 5 2 5 1]S-So I can't wear it![n]Wear it yourself![n][f 0 4][e]

[msg MSG_4A_NPC004_01 [Male Student]]
[f 0 8 65278][f 1 31]Are you here for the arcade?[n][f 0 4][e]
[f 0 8 65278][f 1 31]If you wanna know about the games[n]here, I can tell you all about 'em.[n][f 0 4][e]

[sel MSG_4A_NPC004_01_SEL top]
[f 0 8 65278][f 1 31]"Sure."[e]
[f 0 8 65278][f 1 31]"Nah."[e]

[msg MSG_4A_NPC004_02 [Male Student]]
[f 0 8 65278][f 1 31]Today, you can use either the[n]Print Club booth or the punching[n]machine.[n][f 0 4][e]
[f 0 8 65278][f 1 31]The Print Club stickers bring out[n]the best in people, so it boosts[n]your charm.[n][f 0 4][e]
[f 0 8 65278][f 1 31]The punching machine is pretty self-[n]explanatory. You'll gain strength[n]if you use it.[n][f 0 4][e]
[f 0 8 65278][f 1 31]That about covers it.[n][f 0 4][e]

[msg MSG_4A_NPC004_03 [Male Student]]
[f 0 8 65278][f 1 31]Today, you can play either Horror[n]House or Mole Whackers.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Horror House is pretty scary...[n]If you last more than a few minutes[n]in there, your courage goes up.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Mole Whackers tests your twitch[n]reflexes, so it increases your speed.[n][f 0 4][e]
[f 0 8 65278][f 1 31]That about covers it.[n][f 0 4][e]

[msg MSG_4A_NPC004_04 [Male Student]]
[f 0 8 65278][f 1 31]You can play the quiz game today[n]or try the fortune-teller machine.[n][f 0 4][e]
[f 0 8 65278][f 1 31]The quiz game is pretty difficult...[n]It's a good way to improve your[n]academics.[n][f 0 4][e]
[f 0 8 65278][f 1 31]I'm not sure what good the fortune-[n]teller machine does, but I hear you[n]gain some kinda magic powers...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Well, that about covers it.[n][f 0 4][e]

[msg MSG_4A_NPC004_05 [Male Student]]
[f 0 8 65278][f 1 31]Today, you can use the punching[n]machine, fortune-teller machine, or[n]play Mole Whackers.[n][f 0 4][e]
[f 0 8 65278][f 1 31]The punching machine is pretty self-[n]explanatory. You'll gain strength[n]if you use it.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Mole Whackers tests your twitch[n]reflexes, so it increases your speed.[n][f 0 4][e]
[f 0 8 65278][f 1 31]I'm not sure what good the fortune-[n]teller machine does, but I hear you[n]gain some kinda magic powers...[n][f 0 4][e]

[msg MSG_4A_NPC004_06 [Male Student]]
[f 0 8 65278][f 1 31]The games are pretty addicting! You[n]can end up pumping in lots of coins,[n]but you get something in return.[n][f 0 4][e]
[f 0 8 65278][f 1 31]My strategy is to play the games that[n]polish my charm and reflexes.[n][f 0 4][e]

[msg MSG_4B_NPC004_01 [Male Student]]
[f 0 8 65278][f 1 31]See that weirdo over there?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Isn't he a victim of those mysterious[n]incidents...?[n][f 0 4][e]
[f 0 8 65278][f 1 31]It's so creepy...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Hey, did you come for the arcade?[n][f 0 4][e]
[f 0 8 65278][f 1 31]If you wanna know about the games,[n]I can tell you all about 'em.[n][f 0 4][e]

[msg MSG_5B_NPC004_01 [Male Student]]
[f 0 8 65278][f 1 31]Arcade games only start when you[n]put in a coin, not like the home[n]consoles where you turn them on.[n][f 0 4][e]
[f 0 8 65278][f 1 31]I didn't realize how they worked[n]until my friend told me.[n][f 0 4][e]
[f 0 8 65278][f 1 31]What about you? You got any friends[n]who help you out like that?[n][f 0 4][e]

[sel MSG_5B_NPC004_01_SEL top]
[f 0 8 65278][f 1 31]"Yeah."[e]
[f 0 8 65278][f 1 31]"I don't need friends."[e]

[msg MSG_5B_NPC004_02 [Male Student]]
[f 0 8 65278][f 1 31]That's cool. Be nice to them.[n][f 0 4][e]

[msg MSG_5B_NPC004_03 [Male Student]]
[f 0 8 65278][f 1 31]You sure, man?[n][f 0 4][e]
[f 0 8 65278][f 1 31]I mean, what if you come up[n]against a problem you can't[n]solve on your own?[n][f 0 4][e]
[f 0 8 65278][f 1 31]No one's perfect... You should[n]have friends who can help, in[n]case you get into a jam.[n][f 0 4][e]

[msg MSG_8B_NPC004_01 [Male Student]]
[f 0 8 65278][f 1 31]This machine has some peculiar[n]quirks...[n][f 0 4][e]
[f 0 8 65278][f 1 31]The crane's claw is close to the[n]player, so the opening and closing[n]motions are limited...[n][f 0 4][e]

[sel MSG_8B_NPC004_01_SEL top]
[f 0 8 65278][f 1 31]"How'd you learn that?"[e]
[f 0 8 65278][f 1 31]"I see."[e]

[msg MSG_8B_NPC004_02 [Male Student]]
[f 0 8 65278][f 1 31]One of the employees secretly told[n]me. It seems they already consider[n]me a regular.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Maybe you should get to know[n]the guys here. You might learn[n]something.[n][f 0 4][e]

[msg MSG_8B_NPC004_03 [Male Student]]
[f 0 8 65278][f 1 31]I guess I can't force people[n]to care...[n][f 0 4][e]

[msg MSG_9B_NPC004_01 [Male Student]]
[f 0 8 65278][f 1 31]Hey, guess what! I finally got[n]the prize![n][f 0 4][e]

[sel MSG_9B_NPC004_01_SEL top]
[f 0 8 65278][f 1 31]"Congrats."[e]
[f 0 8 65278][f 1 31]"Whatever."[e]

[msg MSG_9B_NPC004_02 [Male Student]]
[f 0 8 65278][f 1 31]I basically just lucked into it,[n]but I'm still psyched.[n][f 0 4][e]
[f 0 8 65278][f 1 31]I'll keep training until I can[n]get the prize even without luck![n][f 0 4][e]

[msg MSG_9B_NPC004_03 [Male Student]]
[f 0 8 65278][f 1 31]Dude... That was uncalled for![n][f 0 4][e]
[f 0 8 65278][f 1 31]If you keep acting like that,[n]you'll end up with no friends.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Mark my words, man.[n][f 0 4][e]

[msg MSG_1N_NPC000_01 [Old Man]]
[f 0 8 65278][f 1 31]Even if email is in vogue today,[n]I'm still happy to get New Year's[n]cards.[n][f 0 4][e]
[f 0 8 65278][f 1 31]You got any friends you send[n]New Year's cards to?[n][f 0 4][e]

[sel MSG_1N_NPC000_01_SEL top]
[f 0 8 65278][f 1 31]"A few."[e]
[f 0 8 65278][f 1 31]"No..."[e]

[msg MSG_1N_NPC000_02 [Old Man]]
[f 0 8 65278][f 1 31]You ever heard the rhyme? "Make new[n]friends, but keep the old; One is[n]silver, and the other's gold."[n][f 0 4][e]

[msg MSG_1N_NPC000_03 [Old Man]]
[f 0 8 65278][f 1 31]At your age? Now that's depressing.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Your New Year's resolution oughta[n]be to meet new people, then.[n][f 0 4][e]

[msg MSG_4A_NPC005_01 [Woman]]
[f 0 8 65278][f 1 31]Hello, young man. Say...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Have you heard anything about this[n]business of ordinary, healthy people[n]changing overnight?[n][f 0 4][e]

[sel MSG_4A_NPC005_01_SEL top]
[f 0 8 65278][f 1 31]"Yeah, I know about it."[e]
[f 0 8 65278][f 1 31]"Huh?"[e]

[msg MSG_4A_NPC005_02 [Woman]]
[f 0 8 65278][f 1 31]Well, obviously. It's all over TV.[n][f 0 4][e]

[msg MSG_4A_NPC005_03 [Woman]]
[f 0 8 65278][f 1 31]Hey! You don't sound concerned[n]at all![n][f 0 4][e]
[f 0 8 65278][f 1 31]How can you not know about this?[n]You live here![n][f 0 4][e]

[msg MSG_7A_NPC002_01 [Man]]
[f 0 8 65278][f 1 31]Want to know something cool?[n][f 0 4][e]
[f 0 8 65278][f 1 31]You know this place is called the[n]Paulownia Mall, right? Well, you[n]know how it got that name?[n][f 0 4][e]

[sel MSG_7A_NPC002_01_SEL top]
[f 0 8 65278][f 1 31]"Yeah, I know."[e]
[f 0 8 65278][f 1 31]"No, tell me."[e]

[msg MSG_7A_NPC002_02 [Man]]
[f 0 8 65278][f 1 31]Wow, you're not some average[n]student. Kids like you give me[n]hope for the future.[n][f 0 4][e]

[msg MSG_7A_NPC002_03 [Man]]
[f 0 8 65278][f 1 31]A paulownia is a type of plant.[n]The "Kiri" in its Japanese name is[n]the same one as in "Kirijo."[n][f 0 4][e]
[f 0 8 65278][f 1 31]Since this place is under the[n]ownership of the Kirijo Group...[n]Get it?[n][f 0 4][e]
[f 0 8 65278][f 1 31]I may look like a slacker salaryman,[n]but I know some surprising things.[n][f 0 4][e]

[msg MSG_4A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]Oh my! How did I forget to buy[n]shampoo!?[n][f 0 4][e]

[msg MSG_4A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]No rush. Just wait for the sale.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]Isn't Saturday the sale day at[n]Aohige Pharmacy?[n][f 0 4][e]

[msg MSG_4A_NPC007_02 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Aohige Pharmacy has sales on[n]Saturday, right?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]Today's Saturday... We should stop[n]by there later![n][f 0 4][e]

[msg MSG_5A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]My eldest is starting to be[n]fashionable...[n][f 0 4][e]
[f 0 8 65278][f 1 31]I was cleaning his room and found[n]a ring. What I wonder is, how'd he[n]buy that on his allowance...?[n][f 0 4][e]

[msg MSG_5A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]He must have got it from Be Blue V.[n]It's the accessory shop next to the[n]police station.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]My son was telling me they have[n]regular sales every Sunday.[n][f 0 4][e]

[msg MSG_5B_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]Last week was my 15th wedding[n]anniversary.[n][f 0 4][e]
[f 0 8 65278][f 1 31]But my lousy husband didn't give me[n]anything! He didn't even remember it[n]was our anniversary![n][f 0 4][e]

[msg MSG_5B_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Seriously? Japanese men are so[n]clueless when it comes to those[n]things.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]Even a single flower from Rafflesia[n]would make us happy.[n][f 0 4][e]

[msg MSG_6A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]Did you hear? That uh, what was it,[n]the Apathy Syndrome?[n][f 0 4][e]
[f 0 8 65278][f 1 31]There was a victim at Gekkoukan.[n]He was friends with my son's[n]senpai.[n][f 0 4][e]

[msg MSG_6A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]A victim in your own neighborhood?[n]Oh my... I guess we can't say it's[n]none of our business now.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]My son's teacher's relative's son's[n]calligraphy master caught Apathy[n]Syndrome too.[n][f 0 4][e]

[msg MSG_6B_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]I'm getting hungry...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Should we stop somewhere and grab[n]a bite to eat?[n][f 0 4][e]

[msg MSG_6B_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Ooh, let's get some of Octopia's[n]takoyaki![n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]But it's at the Iwatodai strip[n]mall... We'll have to take the[n]monorail.[n][f 0 4][e]

[msg MSG_7A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]I heard from my son that there's[n]this freaky website on the Internet.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Apparently, you can have someone[n]carry out revenge for you.[n][f 0 4][e]

[msg MSG_7A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]They have online revenge agents now!?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]I don't know much about computers,[n]but that sounds strange...[n][f 0 4][e]

[msg MSG_7B_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]I get tired of coming up with new[n]things to put into my son's lunch.[n][f 0 4][e]
[f 0 8 65278][f 1 31]My family always complains when[n]I give them the same dish, so I'm[n]always looking for something new.[n][f 0 4][e]

[msg MSG_7B_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]My friend told me about her kid at[n]Gekkoukan, who ordered a Porkchop[n]Sandwich from the Student Shop...[n][f 0 4][e]
[f 0 8 65278][f 1 31]He complained about the porkchop[n]in it, of all things, so she got[n]angry at him.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]She told him, "If you don't like[n]the meat, order sweet pastries or[n]Tricolor Cakebread from now on![n][f 0 4][e]

[msg MSG_8A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]Our kids are off on their summer[n]vacation. I'm exhausted from making[n]their meals every day.[n][f 0 4][e]

[msg MSG_8A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]One of the women in my neighborhood[n]says she precooks massive amounts[n]of udon.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Then she rotates between sesame[n]dressing, ponzu, and shredded daikon[n]so it always tastes differently.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]I figure we housewives need summer[n]vacation, too, so I decided to copy[n]her method.[n][f 0 4][e]

[msg MSG_0731_NPC006_01 [Long-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]Don't those kids look strange?[n]That one near the clubhouse...[n]Is he from Gekkoukan?[n][f 0 4][e]
[f 0 8 65278][f 1 31]They look sort of slack, and[n]unmoving... Is he being lazy[n]since it's summer vacation?[n][f 0 4][e]

[msg MSG_0731_NPC007_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]One of the women in my neighborhood[n]has a kid who goes to Gekkoukan...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]But she's energetic and sweet,[n]very different from those kids.[n][f 0 4][e]

[msg MSG_8B_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]My son became nocturnal over[n]summer vacation.[n][f 0 4][e]
[f 0 8 65278][f 1 31]He wakes up in the afternoon and[n]leaves at night, and usually[n]doesn't come back until sunrise.[n][f 0 4][e]

[msg MSG_8B_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Where do they go that late at[n]night...? That Escapade club?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]The security is too lax at those[n]kinds of places. I heard high school[n]kids just need uniforms to get in.[n][f 0 4][e]

[msg MSG_9A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]I think the hot summer sun got[n]to me...[n][f 0 4][e]
[f 0 8 65278][f 1 31]See? My arms are tanned, and my[n]skin is all rough.[n][f 0 4][e]

[msg MSG_9A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Do you know the ramen restaurant[n]Hagakure at the Iwatodai strip mall?[n][f 0 4][e]
[f 0 8 65278][f 1 31]The ramen they sell there has plenty[n]of collagen to boost your beauty![n]That's what I heard, anyway.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]If you make your skin more youthful,[n]I bet your mind will follow, and[n]your husband will love you more![n][f 0 4][e]

[msg MSG_9B_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]A woman in my neighborhood said[n]part of her roof was destroyed by[n]the typhoon.[n][f 0 4][e]
[f 0 8 65278][f 1 31]No matter how much we try to prevent[n]disasters, there's no way we can[n]completely guard against them...[n][f 0 4][e]

[msg MSG_9B_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Well, I don't know. You can't trust[n]those building contractors, you[n]know.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]It could be that her house was[n]just made of cheap, non-regulation[n]materials.[n][f 0 4][e]

[msg MSG_0927_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]That kid in front of the club[n]bothers me... He's so motionless.[n][f 0 4][e]
[f 0 8 65278][f 1 31]He's from Gekkoukan, right? It's[n]been a while since the second term[n]started.[n][f 0 4][e]

[msg MSG_0927_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]I understand how relaxed they are[n]since autumn has just begun...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]But they seem too relaxed to me.[n][f 0 4][e]

[msg MSG_10A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]I was thinking of having my older[n]son take the Gekkoukan entrance[n]exam, but...[n][f 0 4][e]
[f 0 8 65278][f 1 31]I don't want him to go to[n]a dangerous school. Maybe[n]I should reconsider...[n][f 0 4][e]

[msg MSG_10A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]You mean the Gekkoukan student[n]who was in that fighting incident?[n]He died, right!?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]I feel sorry for him... He was too[n]young to die. How could that have[n]happened?[n][f 0 4][e]

[msg MSG_10B_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]You see Mandragora, the karaoke[n]studio at the top of those stairs?[n][f 0 4][e]
[f 0 8 65278][f 1 31]I saw someone coming out of there[n]by himself. Was he singing alone...?[n][f 0 4][e]

[msg MSG_10B_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Well, it's not that weird...[n]But I bet you'd draw some strange[n]looks from the staff.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]It builds courage, in a way, to do[n]whatever you want, no matter what[n]other people may think.[n][f 0 4][e]

[msg MSG_1105_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]H-Hey... Those motionless kids[n]near the club...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Are they... Are they the ones[n]with that Apathy Syndrome[n]everyone is talking about?[n][f 0 4][e]

[msg MSG_1105_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Oh, you're worrying too much.[n]Aren't they just relaxing?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]Although... They have been like that[n]for a while. Are they going to stay[n]there forever...?[n][f 0 4][e]

[msg MSG_11A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]I heard the head of the Kirijo[n]Group passed away...[n][f 0 4][e]
[f 0 8 65278][f 1 31]His young daughter is all alone in[n]the world now. He must regret having[n]to leave her so early.[n][f 0 4][e]

[msg MSG_11A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Well, officially, his death was[n]an accident. But judging by his[n]fierce face...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]I think it was foul play. Maybe[n]it was gang-related...?[n][f 0 4][e]

[msg MSG_11B_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]Your daughter is looking wonderful[n]lately. She came over to say hi to[n]me, and I didn't recognize her.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Is she getting married? Or did she[n]just get a boyfriend?[n][f 0 4][e]

[msg MSG_11B_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Oh, it's nothing like that...[n]Do you see the Chagall coffeeshop[n]next to the club?[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]My daughter said that just drinking[n]their coffee increases your Charm.[n]It's pheromones, or something...[n][f 0 4][e]

[msg MSG_12A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]My son isn't stressed at all, even[n]with exams coming up... I'm a little[n]worried about him.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Do you know the Wild-duck Burger in[n]the Iwatodai strip mall? He's trying[n]something new on the menu every day.[n][f 0 4][e]

[msg MSG_12A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Is that the place that uses the[n]mysterious ingredients? I doubt[n]they'd use anything inedible...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]But I wouldn't be able to eat there.[n]I don't have the courage those kids[n]have to try weird foods.[n][f 0 4][e]

[msg MSG_12B_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]My eldest is having his exams soon.[n]The atmosphere at home is very[n]tense now...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Even I get tense, remembering the[n]time when I took my own exams...[n][f 0 4][e]

[msg MSG_12B_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]I took my kid to the Iwatodai[n]strip mall, and we had lunch[n]together at Wakatsu.[n][f 0 4][e]
[f 0 8 65278][f 1 31]My husband saw an ad for them that[n]talked about young prodigies, or[n]something...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]I don't know if my kid got smarter[n]from eating the meal, but on the[n]other hand, he did pass the exam.[n][f 0 4][e]

[msg MSG_1N_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]Did you see that graffiti incident[n]on the news?[n][f 0 4][e]
[f 0 8 65278][f 1 31]Is that red paint on the wall[n]part of it?[n][f 0 4][e]

[msg MSG_1N_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Well, it's like those motorcycle[n]gangs who always to go Mt. Fuji[n]every New Year's Eve.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]They fall into that mob mentality,[n]and don't realize that what they're[n]doing is wrong.[n][f 0 4][e]

[msg MSG_1A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]Did you see the news? Some thug[n]broke into the hall where the[n]university testing is held...[n][f 0 4][e]
[f 0 8 65278][f 1 31]My eldest is entering high school[n]next month... I-I'm worried.[n][f 0 4][e]

[msg MSG_1A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]One of my neighbors' sons went to[n]that assembly hall...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]He said people there were screaming[n]"Nyx" or something, with angry[n]looks on their faces.[n][f 0 4][e]

[msg MSG_1B_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]You know how that cult is spreading[n]all over the world now?[n][f 0 4][e]
[f 0 8 65278][f 1 31]D-Does that mean there are cultists[n]in this mall right now...?[n][f 0 4][e]

[msg MSG_1B_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]My neighbor's kid was asked about[n]the Fall, too, I think...[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]I-I think there really might be[n]some cultists here... The people[n]around us look suspicious...[n][f 0 4][e]

[msg MSG_3A_NPC006_01 [Short-haired Housewife]]
[f 0 8 65278][f 1 31][f 1 28 6 3 5 0 0]Things have really calmed down over[n]the last month. It's like that cult[n]thing never happened.[n][f 0 4][e]
[f 0 8 65278][f 1 31]All I'm worried about now is my[n]son's exam result. He says he's[n]confident, but we'll see.[n][f 0 4][e]

[msg MSG_3A_NPC007_01 [Housewife with Braids]]
[f 0 8 65278][f 1 31][f 1 28 7 3 5 0 0]Yeah, those motionless people are[n]all but gone, and everything's[n]back to normal.[n][f 0 4][e]
[f 0 8 65278][f 1 31][f 1 28 7 0 5 65535 15]I'm glad that all I have to worry[n]about is my son's university[n]entrance exams next year.[n][f 0 4][e]

[msg MSG_8A_NPC003_01 [Male Student]]
[f 0 8 65278][f 1 31]Sometimes, that girl over there[n]who's stalking me loses my trail.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Then what...? I don't know why, but[n]I get anxious when that happens.[n][f 0 4][e]
[f 0 8 65278][f 1 31]Wait a sec... Am I obsessed with[n]her, too...?[n][f 0 4][e]

[msg MSG_KAGE_01_01 [Male Student]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_01_02 [Male Student]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ah...[n]Uu...[n][f 0 4][e]

[msg MSG_KAGE_01_03 [Male Student]]
[f 0 8 65278][f 1 31]Uhh...[n]Ah...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ahh...[n][f 0 4][e]

[msg MSG_KAGE_01_04 [Male Student]]
[f 0 8 65278][f 1 31]Uhaaa...[n]Auuu...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_01_05 [Male Student]]
[f 0 8 65278][f 1 31]Uhh...[n]Uhwa...[n]Aah...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ahhh...[n][f 0 4][e]

[msg MSG_KAGE_01_06 [Male Student]]
[f 0 8 65278][f 1 31]Ahhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uu...[n]Uhh...[n][f 0 4][e]

[msg MSG_KAGE_01_07 [Male Student]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uaaaah...[n][f 0 4][e]

[msg MSG_KAGE_01_08 [Male Student]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uh...[n]Uhhhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_01_09 [Male Student]]
[f 0 8 65278][f 1 31]Uh...[n]Uh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uhhhhhh...[n]Uh...[n][f 0 4][e]

[msg MSG_KAGE_01_10 [Male Student]]
[f 0 8 65278][f 1 31]Uaaah...[n]Ahh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n]Uhhh...[n][f 0 4][e]

[msg MSG_KAGE_02_01 [Female Student]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_02_02 [Female Student]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ah...[n]Uu...[n][f 0 4][e]

[msg MSG_KAGE_02_03 [Female Student]]
[f 0 8 65278][f 1 31]Uhh...[n]Ah...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ahh...[n][f 0 4][e]

[msg MSG_KAGE_02_04 [Female Student]]
[f 0 8 65278][f 1 31]Uhaaa...[n]Auuu...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_02_05 [Female Student]]
[f 0 8 65278][f 1 31]Uhh...[n]Uhwa...[n]Aah...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ah...[n][f 0 4][e]

[msg MSG_KAGE_02_06 [Female Student]]
[f 0 8 65278][f 1 31]Ahhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uu...[n]Uhh...[n][f 0 4][e]

[msg MSG_KAGE_02_07 [Female Student]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uaaaah...[n][f 0 4][e]

[msg MSG_KAGE_02_08 [Female Student]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uh...[n]Uhhhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_02_09 [Female Student]]
[f 0 8 65278][f 1 31]Uh...[n]Uhhhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uhhhhhh...[n]Uh...[n][f 0 4][e]

[msg MSG_KAGE_02_10 [Female Student]]
[f 0 8 65278][f 1 31]Uaaah...[n]Ahh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n]Uhhh...[n][f 0 4][e]

[msg MSG_KAGE_03_01 [Man]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_03_02 [Man]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ah...[n]Uu...[n][f 0 4][e]

[msg MSG_KAGE_03_03 [Man]]
[f 0 8 65278][f 1 31]Uhh...[n]Ah...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ahh...[n][f 0 4][e]

[msg MSG_KAGE_03_04 [Man]]
[f 0 8 65278][f 1 31]Uhaaa...[n]Auuu...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_03_05 [Man]]
[f 0 8 65278][f 1 31]Uhh...[n]Uhwa...[n]Aah...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ah...[n][f 0 4][e]

[msg MSG_KAGE_03_06 [Man]]
[f 0 8 65278][f 1 31]Ahhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uu...[n]Uhh...[n][f 0 4][e]

[msg MSG_KAGE_03_07 [Man]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uaaaah...[n][f 0 4][e]

[msg MSG_KAGE_03_08 [Man]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uh...[n]Uhhhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_03_09 [Man]]
[f 0 8 65278][f 1 31]Uh...[n]Uhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uhhhhhh...[n]Uh...[n][f 0 4][e]

[msg MSG_KAGE_03_10 [Man]]
[f 0 8 65278][f 1 31]Uaaah...[n]Ahh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n]Uhhh...[n][f 0 4][e]

[msg MSG_KAGE_04_01 [Woman]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_04_02 [Woman]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ah...[n]Uu...[n][f 0 4][e]

[msg MSG_KAGE_04_03 [Woman]]
[f 0 8 65278][f 1 31]Uhh...[n]Ah...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ahh...[n][f 0 4][e]

[msg MSG_KAGE_04_04 [Woman]]
[f 0 8 65278][f 1 31]Uhaaa...[n]Auuu...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_04_05 [Woman]]
[f 0 8 65278][f 1 31]Uhh...[n]Uhwa...[n]Aah...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Ah...[n][f 0 4][e]

[msg MSG_KAGE_04_06 [Woman]]
[f 0 8 65278][f 1 31]Ahhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uu...[n]Uhh...[n][f 0 4][e]

[msg MSG_KAGE_04_07 [Woman]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uaaaah...[n][f 0 4][e]

[msg MSG_KAGE_04_08 [Woman]]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uh...[n]Uhhhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n][f 0 4][e]

[msg MSG_KAGE_04_09 [Woman]]
[f 0 8 65278][f 1 31]Uh...[n]Uhh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]Uhhhhhh...[n]Uh...[n][f 0 4][e]

[msg MSG_KAGE_04_10 [Woman]]
[f 0 8 65278][f 1 31]Uaaah...[n]Ahh...[n][f 0 4][e]
[f 0 8 65278][f 1 31]......[n]Uhhh...[n][f 0 4][e]

[msg MSG_KAGE_FIRST]
[f 0 8 65278][f 1 31]> It's one of The Lost--victim of[n]the Apathy Syndrome that's causing[n]such a stir.[n][f 0 4][e]
[f 0 8 65278][f 1 31]> You cannot get a meaningful[n]response out of this person.[n][f 0 4][e]

