[msg DormTime]
[f 0 8 -258][f 1 31]If you go back into the dorm,then it will[n]automatically become nighttime.[n][f 0 4][e]
[f 0 8 -258][f 1 31]> Will you go back to the dorm now?[n][f 0 4][e]

[sel EnterDorm top]
[f 0 8 -258][f 1 31]Enter[e]
[f 0 8 -258][f 1 31]Don't go back yet[e]

[msg RoomTime]
[f 0 8 -258][f 1 31]If you go to your room,then it will[n]automatically becomelate night.[n][f 0 4][e]
[f 0 8 -258][f 1 31]> Will you go back to your room now?[n][f 0 4][e]

[sel EnterRoom top]
[f 0 8 -258][f 1 31]Enter[e]
[f 0 8 -258][f 1 31]Not yet[e]